//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxActorFlag {
  VISUALIZATION = (1 << 0),
  DISABLE_GRAVITY = (1 << 1),
  SEND_SLEEP_NOTIFIES = (1 << 2),
  DISABLE_SIMULATION = (1 << 3)
}

}
