//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxConcreteType {
  UNDEFINED,
  HEIGHTFIELD,
  CONVEX_MESH,
  TRIANGLE_MESH_BVH33,
  TRIANGLE_MESH_BVH34,
  RIGID_DYNAMIC,
  RIGID_STATIC,
  SHAPE,
  MATERIAL,
  CONSTRAINT,
  AGGREGATE,
  ARTICULATION,
  ARTICULATION_REDUCED_COORDINATE,
  ARTICULATION_LINK,
  ARTICULATION_JOINT,
  ARTICULATION_JOINT_REDUCED_COORDINATE,
  PRUNING_STRUCTURE,
  BVH_STRUCTURE,
  PHYSX_CORE_COUNT,
  FIRST_PHYSX_EXTENSION = 256,
  FIRST_VEHICLE_EXTENSION = 512,
  FIRST_USER_EXTENSION = 1024
}

}
