//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxContactPairHeaderFlag {
  REMOVED_ACTOR_0 = (1 << 0),
  REMOVED_ACTOR_1 = (1 << 1)
}

}
