//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxD6Axis {
  X = 0,
  Y = 1,
  Z = 2,
  TWIST = 3,
  SWING1 = 4,
  SWING2 = 5,
  COUNT = 6
}

}
