//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxDefaultMemoryInputData : PxInputData {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PxDefaultMemoryInputData(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NativePINVOKE.PxDefaultMemoryInputData_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxDefaultMemoryInputData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxDefaultMemoryInputData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.destroy();
    }
  }

  public PxDefaultMemoryInputData(global::System.IntPtr data, uint length) : this(NativePINVOKE.new_PxDefaultMemoryInputData(data, length), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint read(global::System.IntPtr dest, uint count) {
    uint ret = NativePINVOKE.PxDefaultMemoryInputData_read(swigCPtr, dest, count);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override uint getLength() {
    uint ret = NativePINVOKE.PxDefaultMemoryInputData_getLength(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void seek(uint pos) {
    NativePINVOKE.PxDefaultMemoryInputData_seek(swigCPtr, pos);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint tell() {
    uint ret = NativePINVOKE.PxDefaultMemoryInputData_tell(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
