//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxDefaultMemoryOutputStream : PxOutputStream {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PxDefaultMemoryOutputStream(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NativePINVOKE.PxDefaultMemoryOutputStream_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxDefaultMemoryOutputStream obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxDefaultMemoryOutputStream(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.destroy();
    }
  }

  public PxDefaultMemoryOutputStream() : this(NativePINVOKE.new_PxDefaultMemoryOutputStream(), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint write(global::System.IntPtr src, uint count) {
    uint ret = NativePINVOKE.PxDefaultMemoryOutputStream_write(swigCPtr, src, count);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint getSize() {
    uint ret = NativePINVOKE.PxDefaultMemoryOutputStream_getSize(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual global::System.IntPtr getData() {
    global::System.IntPtr ret = NativePINVOKE.PxDefaultMemoryOutputStream_getData(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
