//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
public partial struct PxFilterData {

  public uint word0,word1,word2,word3;

  internal global::System.IntPtr swigCPtr {
    get { unsafe { fixed(PxFilterData* p = &this) return (global::System.IntPtr)p; } }
  }

  internal PxFilterData(global::System.IntPtr ptr, bool unused) {
      //this = global::System.Runtime.InteropServices.Marshal.PtrToStructure<PxFilterData>(ptr);
      unsafe { this = *(PxFilterData*)ptr; }
  }
    
  public PxFilterData(PxEMPTY arg0) : this(NativePINVOKE.new_PxFilterData__SWIG_0((int)arg0), true) { 
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve(); }
  public PxFilterData( PxFilterData  fd) : this(NativePINVOKE.new_PxFilterData__SWIG_1( fd.swigCPtr ), true) { 
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve(); }
  public PxFilterData(uint w0, uint w1, uint w2, uint w3) : this(NativePINVOKE.new_PxFilterData__SWIG_2(w0, w1, w2, w3), true) { 
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve(); }
  public void setToDefault() {
    NativePINVOKE.PxFilterData_setToDefault(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
