//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxMaterialFlag {
  DISABLE_FRICTION = 1 << 0,
  DISABLE_STRONG_FRICTION = 1 << 1,
  IMPROVED_PATCH_FRICTION = 1 << 2
}

}
