//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxQueryFlag {
  STATIC = (1 << 0),
  DYNAMIC = (1 << 1),
  PREFILTER = (1 << 2),
  POSTFILTER = (1 << 3),
  ANY_HIT = (1 << 4),
  NO_BLOCK = (1 << 5),
  RESERVED = (1 << 15)
}

}
