//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxSceneFlag {
  ENABLE_ACTIVE_ACTORS = (1 << 0),
  ENABLE_CCD = (1 << 1),
  DISABLE_CCD_RESWEEP = (1 << 2),
  ADAPTIVE_FORCE = (1 << 3),
  ENABLE_PCM = (1 << 6),
  DISABLE_CONTACT_REPORT_BUFFER_RESIZE = (1 << 7),
  DISABLE_CONTACT_CACHE = (1 << 8),
  REQUIRE_RW_LOCK = (1 << 9),
  ENABLE_STABILIZATION = (1 << 10),
  ENABLE_AVERAGE_POINT = (1 << 11),
  EXCLUDE_KINEMATICS_FROM_ACTIVE_ACTORS = (1 << 12),
  ENABLE_GPU_DYNAMICS = (1 << 13),
  ENABLE_ENHANCED_DETERMINISM = (1 << 14),
  ENABLE_FRICTION_EVERY_ITERATION = (1 << 15),
  MUTABLE_FLAGS = (1 << 0)|(1 << 12)
}

}
