//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxShapeFlag {
  SIMULATION_SHAPE = (1 << 0),
  SCENE_QUERY_SHAPE = (1 << 1),
  TRIGGER_SHAPE = (1 << 2),
  VISUALIZATION = (1 << 3)
}

}
