//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxSweepBuffer : PxSweepCallback {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PxSweepBuffer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NativePINVOKE.PxSweepBuffer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxSweepBuffer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxSweepBuffer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.destroy();
    }
  }

  public PxSweepBuffer(PxSweepHit aTouches, uint aMaxNbTouches) : this(NativePINVOKE.new_PxSweepBuffer__SWIG_0(PxSweepHit.getCPtr(aTouches), aMaxNbTouches), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxSweepBuffer(PxSweepHit aTouches) : this(NativePINVOKE.new_PxSweepBuffer__SWIG_1(PxSweepHit.getCPtr(aTouches)), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxSweepBuffer() : this(NativePINVOKE.new_PxSweepBuffer__SWIG_2(), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getNbAnyHits() {
    uint ret = NativePINVOKE.PxSweepBuffer_getNbAnyHits(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PxSweepHit getAnyHit(uint index) {
    PxSweepHit ret = new PxSweepHit(NativePINVOKE.PxSweepBuffer_getAnyHit(swigCPtr, index), false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getNbTouches() {
    uint ret = NativePINVOKE.PxSweepBuffer_getNbTouches(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PxSweepHit getTouches() {
    global::System.IntPtr cPtr = NativePINVOKE.PxSweepBuffer_getTouches(swigCPtr);
    PxSweepHit ret = (cPtr == global::System.IntPtr.Zero) ? null : new PxSweepHit(cPtr, false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PxSweepHit getTouch(uint index) {
    PxSweepHit ret = new PxSweepHit(NativePINVOKE.PxSweepBuffer_getTouch(swigCPtr, index), false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getMaxNbTouches() {
    uint ret = NativePINVOKE.PxSweepBuffer_getMaxNbTouches(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
