//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxCpuDispatcher {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;
  public object userData;

  internal PxCpuDispatcher(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxCpuDispatcher obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static PxCpuDispatcher getWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
      var wrapper = WrapperCache.find(cPtr);
      if (!(wrapper is PxCpuDispatcher)) {
          wrapper = new PxCpuDispatcher(cPtr, cMemoryOwn);
          WrapperCache.add(cPtr, wrapper);
      }
      return wrapper as PxCpuDispatcher;
  }

  ~PxCpuDispatcher() {
    WrapperCache.remove(swigCPtr.Handle, this);
  }

  public virtual void submitTask(PxBaseTask task) {
    NativePINVOKE.PxCpuDispatcher_submitTask(swigCPtr, PxBaseTask.getCPtr(task));
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual uint getWorkerCount() {
    uint ret = NativePINVOKE.PxCpuDispatcher_getWorkerCount(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PxDefaultCpuDispatcher createDefault(uint numThreads, uint[] affinityMasks) {
    global::System.IntPtr cPtr = NativePINVOKE.PxCpuDispatcher_createDefault__SWIG_0(numThreads, affinityMasks);
    PxDefaultCpuDispatcher ret = (cPtr == global::System.IntPtr.Zero) ? null : PxDefaultCpuDispatcher.getWrapper(cPtr, false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PxDefaultCpuDispatcher createDefault(uint numThreads) {
    global::System.IntPtr cPtr = NativePINVOKE.PxCpuDispatcher_createDefault__SWIG_1(numThreads);
    PxDefaultCpuDispatcher ret = (cPtr == global::System.IntPtr.Zero) ? null : PxDefaultCpuDispatcher.getWrapper(cPtr, false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
