//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxFilterFlag {
  KILL = (1 << 0),
  SUPPRESS = (1 << 1),
  CALLBACK = (1 << 2),
  NOTIFY = (1 << 3)|(1 << 2),
  DEFAULT = 0
}

}
