//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxHitFlag {
  POSITION = (1 << 0),
  NORMAL = (1 << 1),
  UV = (1 << 3),
  ASSUME_NO_INITIAL_OVERLAP = (1 << 4),
  MESH_MULTIPLE = (1 << 5),
  MESH_ANY = (1 << 6),
  MESH_BOTH_SIDES = (1 << 7),
  PRECISE_SWEEP = (1 << 8),
  MTD = (1 << 9),
  FACE_INDEX = (1 << 10),
  DEFAULT = (1 << 0)|(1 << 1)|(1 << 10),
  MODIFIABLE_FLAGS = (1 << 5)|(1 << 7)|(1 << 4)|(1 << 8)
}

}
