//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxJointLinearLimit : PxJointLimitParameters {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PxJointLinearLimit(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NativePINVOKE.PxJointLinearLimit_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxJointLinearLimit obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxJointLinearLimit(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.destroy();
    }
  }

  public float value {
    set {
      NativePINVOKE.PxJointLinearLimit_value_set(swigCPtr, value);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = NativePINVOKE.PxJointLinearLimit_value_get(swigCPtr);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PxJointLinearLimit(PxTolerancesScale scale, float extent, float contactDist) : this(NativePINVOKE.new_PxJointLinearLimit__SWIG_0(PxTolerancesScale.getCPtr(scale), extent, contactDist), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxJointLinearLimit(PxTolerancesScale scale, float extent) : this(NativePINVOKE.new_PxJointLinearLimit__SWIG_1(PxTolerancesScale.getCPtr(scale), extent), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxJointLinearLimit(float extent, PxSpring spring) : this(NativePINVOKE.new_PxJointLinearLimit__SWIG_2(extent, PxSpring.getCPtr(spring)), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public new bool isValid() {
    bool ret = NativePINVOKE.PxJointLinearLimit_isValid(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
