//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxMeshPreprocessingFlag {
  WELD_VERTICES = 1 << 0,
  DISABLE_CLEAN_MESH = 1 << 1,
  DISABLE_ACTIVE_EDGES_PRECOMPUTE = 1 << 2,
  FORCE_32BIT_INDICES = 1 << 3
}

}
