//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxRigidDynamicLockFlag {
  LOCK_LINEAR_X = (1 << 0),
  LOCK_LINEAR_Y = (1 << 1),
  LOCK_LINEAR_Z = (1 << 2),
  LOCK_ANGULAR_X = (1 << 3),
  LOCK_ANGULAR_Y = (1 << 4),
  LOCK_ANGULAR_Z = (1 << 5)
}

}
